package workflow

import (
	"context"
	"fmt"
	"strings"

	"github.com/anton415/mini-agent-orchestrator/internal/artifacts"
	"github.com/anton415/mini-agent-orchestrator/internal/llm"
)

type llmWorkflowStage struct {
	promptFilename string
	outputFilename string
}

var fixedLLMWorkflow = []llmWorkflowStage{
	{
		promptFilename: "prompts/01-normalize-idea.prompt.md",
		outputFilename: "idea.md",
	},
	{
		promptFilename: "prompts/02-generate-spec.prompt.md",
		outputFilename: "spec.md",
	},
	{
		promptFilename: "prompts/03-generate-tasks.prompt.md",
		outputFilename: "tasks.md",
	},
	{
		promptFilename: "prompts/04-review-checklist.prompt.md",
		outputFilename: "review-checklist.md",
	},
}

// LLMGenerator adapts workflow prompt execution to the provider boundary.
type LLMGenerator struct {
	Provider    llm.Provider
	Model       string
	Temperature *float64
	MaxTokens   *int
}

// Generate sends one workflow prompt through the configured provider.
func (generator LLMGenerator) Generate(ctx context.Context, prompt string) (llm.GenerateResponse, error) {
	if generator.Provider == nil {
		return llm.GenerateResponse{}, fmt.Errorf("llm provider is required")
	}
	if strings.TrimSpace(prompt) == "" {
		return llm.GenerateResponse{}, fmt.Errorf("llm prompt is required")
	}

	response, err := generator.Provider.Generate(ctx, llm.GenerateRequest{
		Prompt:      prompt,
		Model:       generator.Model,
		Temperature: generator.Temperature,
		MaxTokens:   generator.MaxTokens,
	})
	if err != nil {
		return llm.GenerateResponse{}, fmt.Errorf("generate llm content: %w", err)
	}

	return response, nil
}

// executeLLMWorkflow executes the fixed idea -> spec -> tasks -> review
// checklist pipeline. Each prompt after the first includes every artifact
// generated by the preceding stages. The returned prompt artifacts contain the
// exact prompt text sent to the provider.
func executeLLMWorkflow(
	ctx context.Context,
	promptItems []artifacts.Artifact,
	generator LLMGenerator,
) (generatedItems []artifacts.Artifact, executedPrompts []artifacts.Artifact, err error) {
	if len(promptItems) != len(fixedLLMWorkflow) {
		return nil, nil, fmt.Errorf(
			"execute LLM workflow: got %d prompt artifacts, want %d",
			len(promptItems),
			len(fixedLLMWorkflow),
		)
	}

	// Validate the complete fixed prompt set before making the first provider
	// call. This prevents a malformed or reordered prompt set from producing a
	// partial workflow execution.
	for index, stage := range fixedLLMWorkflow {
		if promptItems[index].Filename != stage.promptFilename {
			return nil, nil, fmt.Errorf(
				"execute LLM workflow stage %q: got prompt artifact %q, want %q",
				stage.outputFilename,
				promptItems[index].Filename,
				stage.promptFilename,
			)
		}
		if strings.TrimSpace(promptItems[index].Content) == "" {
			return nil, nil, fmt.Errorf(
				"execute LLM workflow stage %q: prompt artifact %q is empty",
				stage.outputFilename,
				stage.promptFilename,
			)
		}
	}

	if ctx == nil {
		ctx = context.Background()
	}

	generatedItems = make([]artifacts.Artifact, 0, len(fixedLLMWorkflow))
	executedPrompts = make([]artifacts.Artifact, 0, len(fixedLLMWorkflow))

	for index, stage := range fixedLLMWorkflow {
		executedPrompt := promptWithGeneratedArtifacts(promptItems[index].Content, generatedItems)

		response, generateErr := generator.Generate(ctx, executedPrompt)
		if generateErr != nil {
			return nil, nil, fmt.Errorf("execute LLM workflow stage %q: %w", stage.outputFilename, generateErr)
		}
		if strings.TrimSpace(response.Content) == "" {
			return nil, nil, fmt.Errorf("execute LLM workflow stage %q: provider returned empty content", stage.outputFilename)
		}

		executedPrompts = append(executedPrompts, artifacts.Artifact{
			Filename: promptItems[index].Filename,
			Content:  executedPrompt,
		})
		generatedItems = append(generatedItems, artifacts.Artifact{
			Filename: stage.outputFilename,
			Content:  response.Content,
		})
	}

	return generatedItems, executedPrompts, nil
}

func promptWithGeneratedArtifacts(basePrompt string, generatedItems []artifacts.Artifact) string {
	if len(generatedItems) == 0 {
		return basePrompt
	}

	var prompt strings.Builder
	prompt.WriteString(basePrompt)
	if !strings.HasSuffix(basePrompt, "\n") {
		prompt.WriteByte('\n')
	}
	prompt.WriteString("\n## Generated upstream artifacts\n\n")
	prompt.WriteString("Use these outputs from earlier workflow stages as the source of truth.\n")

	for _, item := range generatedItems {
		fmt.Fprintf(&prompt, "\n### `%s`\n\n", item.Filename)
		prompt.WriteString(item.Content)
		if !strings.HasSuffix(item.Content, "\n") {
			prompt.WriteByte('\n')
		}
	}

	return prompt.String()
}
