package templates

import (
	"strings"
	"testing"

	"github.com/anton415/mini-agent-orchestrator/internal/artifacts"
	"github.com/anton415/mini-agent-orchestrator/internal/model"
)

// TestRenderAllOrder verifies that RenderAll returns artifacts with the expected
// filenames in a stable, deterministic order across repeated invocations.
func TestRenderAllOrder(t *testing.T) {
	want := []string{
		"idea.md",
		"spec.md",
		"tasks.md",
		"review-checklist.md",
	}

	project := model.NewProject("demo", "a small idea")

	// Render multiple times; the order must be identical every time, which would
	// not hold if RenderAll iterated over a map.
	for i := 0; i < 50; i++ {
		artifacts, err := RenderAll(project)
		if err != nil {
			t.Fatalf("RenderAll returned error: %v", err)
		}

		if len(artifacts) != len(want) {
			t.Fatalf("got %d artifacts, want %d", len(artifacts), len(want))
		}

		for j, name := range want {
			if artifacts[j].Filename != name {
				t.Fatalf("artifact[%d] = %q, want %q", j, artifacts[j].Filename, name)
			}
			if artifacts[j].Content == "" {
				t.Errorf("artifact %q has empty content", name)
			}
		}
	}
}

func TestRenderAllRendersIdeaValues(t *testing.T) {
	project := model.Project{
		Name:    "Template Renderer",
		RawIdea: "Generate markdown artifacts from project input.",
		Version: "v-test",
	}

	artifacts, err := RenderAll(project)
	if err != nil {
		t.Fatalf("RenderAll returned error: %v", err)
	}

	idea := artifactContent(t, artifacts, "idea.md")

	for _, want := range []string{
		project.Name,
		project.RawIdea,
		"Generated by Mini Agent Orchestrator " + project.Version + ".",
	} {
		if !strings.Contains(idea, want) {
			t.Errorf("idea.md does not contain %q\ncontent:\n%s", want, idea)
		}
	}
}

func TestRenderAllTemplatesAvoidGenericTODOs(t *testing.T) {
	project := model.NewProject("demo", "a small idea")

	artifacts, err := RenderAll(project)
	if err != nil {
		t.Fatalf("RenderAll returned error: %v", err)
	}

	for _, artifact := range artifacts {
		if strings.Contains(artifact.Content, "TODO") {
			t.Errorf("%s contains generic TODO marker\ncontent:\n%s", artifact.Filename, artifact.Content)
		}
	}
}

func TestRenderAllTasksTemplateAvoidsRepoSpecificTasks(t *testing.T) {
	project := model.NewProject("demo", "a small idea")

	artifacts, err := RenderAll(project)
	if err != nil {
		t.Fatalf("RenderAll returned error: %v", err)
	}

	tasks := artifactContent(t, artifacts, "tasks.md")
	for _, oldDetail := range []string{
		"Create Go module",
		"Add CLI entrypoint",
		"Read idea from `--idea`",
		"Read idea from `--input`",
		"Prevent overwrite without `--force`",
		"Add `--dry-run`",
	} {
		if strings.Contains(tasks, oldDetail) {
			t.Errorf("tasks.md contains repo-specific task %q\ncontent:\n%s", oldDetail, tasks)
		}
	}
}

func artifactContent(t *testing.T, rendered []artifacts.Artifact, filename string) string {
	t.Helper()

	for _, artifact := range rendered {
		if artifact.Filename == filename {
			return artifact.Content
		}
	}

	t.Fatalf("missing artifact %q", filename)
	return ""
}
